config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  Sidekiq::Web.app_url = "/"

  namespace :admin do
    resources :stations
    resources :fetch_track_infos, only: :update
    resources :ignore_tracks, only: :update
    resources :track_infos, only: %i[edit update]
    resources :events, only: %i[index show]
    resources :tracks, only: [] do
      resources :events, only: %i[index show], controller: "track_events"
    end
  end
  resources :tracks, only: %i[index show]
  resources :track_infos, only: %i[index show]
  root to: "welcome#index"
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id            :bigint           not null, primary key
#  artist        :string           not null
#  played_at     :datetime         not null
#  response      :text
#  slug          :string           not null
#  title         :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  station_id    :bigint           not null
#  track_info_id :bigint
#
# Indexes
#
#  index_tracks_on_slug           (slug)
#  index_tracks_on_station_id     (station_id)
#  index_tracks_on_track_info_id  (track_info_id)
#
# Foreign Keys
#
#  fk_rails_...  (station_id => stations.id)
#
class Track < ApplicationRecord
  belongs_to :station
  belongs_to :track_info, optional: true
  has_many :events, dependent: :destroy
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @track_search = TracksFinder.new(search_params)
    @track_records = @track_search.call.paginate(page: params[:page], per_page: params[:per_page])

    @tracks = TrackPresenter.wrap @track_records
  end

  def show
    @track = TrackPresenter.new Track.find(params[:id])
  end

  private
    def search_params
      if params[:track_info_id].present?
        params.permit(:track_info_id)
      else
        params[:tracks_finder]&.permit(*TracksFinder::FILTERS)
      end
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/index.html.haml
%h1 Tracks

= form_for @track_search, url: tracks_path, :html => {:method => :get, :class => "form-horizontal center"} do |f|
  .form-inline
    .form-group.mb-2
      = f.text_field :artist, class: "form-control", placeholder: "artist", onchange: "this.form.submit();"
    .form-group.mb-2
      = f.select :year, all_years, { include_blank: "select year" } , class: "form-control custom-select", onchange: "this.form.submit();"
    .form-group.mb-2
      = f.select :tag, all_tags, { include_blank: "select tag" } , class: "form-control custom-select", onchange: "this.form.submit();"
    .form-group.mb-2
      = f.select :station_id, all_stations, { include_blank: "select station" }, class: "form-control custom-select", onchange: "this.form.submit();"

.p= "found: #{@track_records.count} "
.table-responsive
  %table.table.table-striped.tracks
    %thead
      %tr
        %th Time
        %th Song
        %th Artist
        %th Album
        %th Year
        %th Tag
        %th Video
        %th Events
        %th Station
        %th

    %tbody
      - @tracks.each do |track|
        %tr{id: "track_#{track.id}"}
          %td= link_to track.played_at, track
          %td= track.title
          %td= track.artist
          %td= track.album
          %td= track.year
          %td= track.main_tag
          %td= track.youtube_link
          %td= link_to :events, admin_track_events_path(track_id: track.id)
          %td= link_to track.station.name, edit_admin_station_path(track.station)
          %td
            = show_button track
            - if track.track_info_id
              = edit_button edit_admin_track_info_path(track.track_info)

= will_paginate @track_records, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
%br

app/views/tracks/show.html.haml
- @attributes = %w[played_at title artist album year main_tag station_name slug response]

%h1 Track

.row
  .col
    %ol.list-group.m-3
      - @attributes.each do | attr |
        %li.list-group-item
          .font-weight-bold= "#{attr.titleize}:"
          = @track.send attr


%p
  %a.btn.btn-secondary{"aria-controls" => "debug", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#debug", :role => "button"} Debug
.row
  .col
    #debug.collapse.multi-collapse
      .card.card-body
        = debug @track.attributes

.row
  .col

    %h3= "#{@track.events.count} Events"

    .p.m-3
      = show_button admin_track_events_path(track_id: @track.id)

.row
  .col
    %h3 Track Info
    = show_button track_info_path(id: @track.track_info_id)


%br
.p
  = back_button root_path