config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  Sidekiq::Web.app_url = "/"

  namespace :admin do
    resources :stations
    resources :fetch_track_infos, only: :update
    resources :ignore_tracks, only: :update
    resources :track_infos, only: %i[edit update]
    resources :events, only: %i[index show]
    resources :tracks, only: [] do
      resources :events, only: %i[index show], controller: "track_events"
    end
  end
  resources :tracks, only: %i[index show]
  resources :track_infos, only: %i[index show]
  root to: "welcome#index"
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id            :bigint           not null, primary key
#  data          :jsonb
#  done_at       :datetime
#  duration      :float
#  meta_data     :jsonb
#  name          :string           not null
#  state         :string           default("ok"), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  station_id    :bigint
#  track_id      :bigint
#  track_info_id :integer
#
# Indexes
#
#  index_events_on_name        (name)
#  index_events_on_state       (state)
#  index_events_on_station_id  (station_id)
#  index_events_on_track_id    (track_id)
#
# Foreign Keys
#
#  fk_rails_...  (track_id => tracks.id)
#
class Event < ApplicationRecord
  STATES = %w[ok failed no_data].freeze
  validates :name, presence: true
  validates :state, presence: true, inclusion: { in: STATES }

  belongs_to :track, optional: true
  belongs_to :track_info, optional: true
  belongs_to :station, optional: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  def index
    @event_search = EventsFinder.new(search_params)
    @event_records = @event_search.call.paginate(page: params[:page], per_page: params[:per_page])

    @events = Admin::EventPresenter.wrap @event_records
  end

  def show
    event_records = Event.find params[:id]
    @event = Admin::EventPresenter.new event_records
  end

  private
    def search_params
      if params[:track_info_id].present?
        params.permit(:track_info_id)
      else
        params[:events_finder]&.permit(*EventsFinder::FILTERS)
      end
    end
end

app/views/admin/events/_event.html.haml
%table.table.table-striped.table-bordered
  %thead.thead-dark
    %tr
      %th
        done_at
      %th
        name
      %th
        state
    %tr
      %td= event.done_at
      %td= event.name
      %td= event.state


%ul.list-group
  %li.list-group-item
    TrackInfo:
    = event.track_info ? link_to(TrackInfoPresenter.new(event.track_info).info, track_info_path(event.track_info)) : ""
  %li.list-group-item
    Track:
    = event.track ? link_to(TrackPresenter.new(event.track).full_name, track_path(event.track)) : ""

  %li.list-group-item
    Station:
    = event.station ? link_to( event.station.name, admin_station_path(event.station)) : ""

%br
.p
  %h3 Data
  - if event.data
    - event.data.each do |k,v|
      .row
        .column.m-3
          %details
            %summary
              = k
            .jumbotron= debug v
  - else
    %h4 NO DATA
.p
  %h3 Meta Data
  %details
    %summary Show
    .jumbotron
      = debug event.meta_data

.row
  .column.m-3
    %p
      %a.btn.btn-secondary{"aria-controls" => "debug", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#debug", :role => "button"} Debug
    .row
      .col
        #debug.collapse.multi-collapse
          .card.card-body
            = debug event.attributes

app/views/admin/events/index.html.haml
%h1 All events

= form_for(@event_search, url: admin_events_path, html: {method: :get, class: "form-horizontal center"}) do |f|
  .form-inline
    .form-group.mb-2
      = f.select :name, all_event_names, { include_blank: "select name" } , class: "form-control custom-select", onchange: "this.form.submit();"
    .form-group.mb-2
      = f.select :state, Event::STATES, { include_blank: "select state" } , class: "form-control custom-select", onchange: "this.form.submit();"
    .form-group.mb-2
      = f.select :station_id, all_stations, { include_blank: "select station" }, class: "form-control custom-select", onchange: "this.form.submit();"
    .form-group.mb-2
      &nbsp;
      = f.submit "Filter", class: "btn btn-primary mb-2"

.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th Date
        %th Name
        %th State
        %th

    %tbody
      - @events.each do |event|
        %tr
          %td= event.done_at
          %td= event.name
          %td= event.state
          %td= show_button admin_event_path(event)

= will_paginate @event_records, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

%br
= back_button root_path

app/views/admin/events/show.html.haml
%h1= "Event: #{@event.name}"

= render "event", event: @event

= back_button admin_events_path