config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  Sidekiq::Web.app_url = "/"

  namespace :admin do
    resources :stations
    resources :fetch_track_infos, only: :update
    resources :ignore_tracks, only: :update
    resources :track_infos, only: %i[edit update]
    resources :events, only: %i[index show]
    resources :tracks, only: [] do
      resources :events, only: %i[index show], controller: "track_events"
    end
  end
  resources :tracks, only: %i[index show]
  resources :track_infos, only: %i[index show]
  root to: "welcome#index"
end

app/models/station.rb
# == Schema Information
#
# Table name: stations
#
#  id             :bigint           not null, primary key
#  enabled        :boolean          default(TRUE)
#  last_logged_at :datetime
#  name           :string           not null
#  playlist_url   :string           not null
#  strategy       :string           not null
#  url            :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_stations_on_last_logged_at  (last_logged_at)
#
class Station < ApplicationRecord
  STRATEGIES = %w[radiobox].freeze
  validates :name, presence: true
  validates :playlist_url, presence: true
  validates :strategy, presence: true, inclusion: { in: STRATEGIES }

  has_many :tracks
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < ApplicationController
  def index
    @station_records = Station.order :name
    @stations = Admin::StationPresenter.wrap @station_records
  end

  def new
    @station = Station.new
  end

  def show
    @station = Admin::StationPresenter.new(Station.find(params[:id]))
  end

  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to admin_stations_path, notice: "Station was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to admin_stations_path, notice: "Station was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def station_params
      params.require(:station).permit(:name, :strategy, :url, :playlist_url, :enabled)
    end
end

app/helpers/admin/stations_helper.rb
module Admin::StationsHelper
end

app/views/admin/stations/_form.html.haml
= form_for [:admin, @station] do |f|
  - if @station.errors.any?
    #error_explanation
      %h2= "#{pluralize(@station.errors.count, "error")}"
      %ul
        - @station.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :playlist_url
    = f.text_field :playlist_url, class: "form-control"
  .form-group
    = f.label :url
    = f.text_field :url, class: "form-control"
  .form-group
    = f.label :strategy
    = f.select :strategy, Station::STRATEGIES, class: "form-control"
  .form-check
    = f.check_box :enabled, class: "form-check-input"
    = f.label :enabled, class: "form-check-label"
 
  .actions
    = submit_button

app/views/admin/stations/edit.html.haml
%h1 Editing Station

= render 'form'

%br.p-b-10
= back_button root_path

app/views/admin/stations/index.html.haml
%h1 Stations Overview

.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Type
        %th Active
        %th Created
        %th Last update
        %th tracks last 24h
        %th all tracks
        %th

    %tbody
      - @stations.each do |station|
        %tr{class: "#{station.problematic? ? 'text-warning' : ' '}"}
          %td= link_to station.name, station.url, target: "_blank"
          %td= link_to station.strategy, station.playlist_url, target: "_blank"
          %td= station.enabled?
          %td= station.created
          %td= station.last_logged_track
          %td= station.tracks_count(24.hours.ago)
          %td= station.tracks_count
          %td
            = edit_button edit_admin_station_path(station)
            = show_button admin_station_path(station)


= add_button new_admin_station_path

app/views/admin/stations/new.html.haml
%h1 New Station

= render 'form'

%br.p-b-10
= back_button root_path

app/views/admin/stations/show.html.haml
%h1 Station

%p
  Name:
  = @station.name


%p
  %a.btn.btn-secondary{"aria-controls" => "debug", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#debug", :role => "button"} Debug
.row
  .col
    #debug.collapse.multi-collapse
      .card.card-body
        = debug @station.attributes