config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  Sidekiq::Web.app_url = "/"

  namespace :admin do
    resources :stations
    resources :fetch_track_infos, only: :update
    resources :ignore_tracks, only: :update
    resources :track_infos, only: %i[edit update]
    resources :events, only: %i[index show]
    resources :tracks, only: [] do
      resources :events, only: %i[index show], controller: "track_events"
    end
  end
  resources :tracks, only: %i[index show]
  resources :track_infos, only: %i[index show]
  root to: "welcome#index"
end

app/models/track_info.rb
# == Schema Information
#
# Table name: track_infos
#
#  id                 :bigint           not null, primary key
#  album              :string
#  album_mbid         :string
#  artist_mbid        :string
#  artist_name        :string           not null
#  ignored            :boolean          default(FALSE), not null
#  mbid               :string
#  name               :string           not null
#  pic_url            :string
#  slug               :string           not null
#  tags               :text             default([]), is an Array
#  wikipedia          :text
#  wikipedia_summary  :text
#  year               :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  album_spotify_id   :string
#  album_wikidata_id  :string
#  artist_spotify_id  :string
#  artist_wikidata_id :string
#  spotify_id         :string
#  wikidata_id        :string
#  youtube_id         :string
#
# Indexes
#
#  index_track_infos_on_slug  (slug)
#  index_track_infos_on_year  (year)
#
class TrackInfo < ApplicationRecord
  has_many :tracks
  has_many :events
end

app/controllers/admin/track_infos_controller.rb
class Admin::TrackInfosController < ApplicationController
  def edit
    @track_info = TrackInfo.find params[:id]
  end

  def update
    @track_info = TrackInfo.find params[:id]

    if UpdateTrackInfo.new(@track_info, track_info_params).call

      redirect_to @track_info, notice: "TrackInfo updated"
    else
      render :edit
    end
  end

  private
    def track_info_params
      params
        .require(:track_info)
        .permit(:name, :album, :year, :artist_name,
          :youtube_id,
          :mbid,

          :wikidata_id,
          :spotify_id,
           :album_mbid,
            :album_spotify_id,
             :album_wikidata_id,
              :artist_spotify_id,
              :artist_wikidata_id,
          :artist_mbid,
          :pic_url)
    end
end

app/controllers/track_infos_controller.rb
class TrackInfosController < ApplicationController
  def show
    track_info_record = TrackInfo.find params[:id]
    @track_info = TrackInfoPresenter.new track_info_record
  end

  def index
  end
end

app/views/track_infos/index.html.haml
%h1 TrackInfos#index
%p Find me in app/views/track_infos/index.html.haml

app/views/track_infos/show.html.haml
%h1 Track Info


-if @track_info.ignored
  %h2.text-danger THIS SONG IS IGNORED

%h2= @track_info.info

.row.mt-3
  .col
    %ol.list-group.m-3
      - TrackInfoPresenter::SHOW_ATTRIBUTES.each do | attr |
        - value = @track_info.send attr
        -if value.present?
          %li.list-group-item
            .font-weight-bold= "#{attr.titleize}:"
            = @track_info.send attr

    %p
      %a.btn.btn-secondary{"aria-controls" => "debug", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#debug", :role => "button"} Debug
    .row
      .col
        #debug.collapse.multi-collapse
          .card.card-body
            = debug @track_info.attributes

.row.mt-3
  .col

    %h3 Stations

    %ol.list-group.m-3
    - @track_info.stations.each do | station |
      %li.list-group-item
        = link_to("#{station.name} - #{@track_info.stations_count station}", admin_station_path(station))


.row.mt-3
  .col
    %h3= "#{@track_info.tracks.count} Tracks"
    = show_button tracks_path(track_info_id: @track_info.id)


.row.mt-3
  .col
    %h3= "#{@track_info.events.count} Events"
    = show_button admin_events_path(track_info_id: @track_info.id)


.row.pt-3
  .col
    %h3 Actions
    = edit_button edit_admin_track_info_path(@track_info)

    = remove_button admin_ignore_track_path(slug: @track_info.slug), "Ignore Track", method: :patch

    = button_with_icon admin_fetch_track_info_path(@track_info), "Fetch Infos", :redo, class: "btn btn-success", method: :patch

.row.pt-3
  .col
    = back_button root_path